version: "3.9"

services:
  dev_server:
    image: zeeguu_api_dev
    environment:
      ZEEGUU_CONFIG: /Zeeguu-API/default_docker.cfg
      ZEEGUU_ES_CONN_STRING: "http://elasticsearch_v8:9200"
      ZEEGUU_EMB_API_CONN_STRING: "http://embedding_api:3654"
      PYTHONUNBUFFERED: 1
      MICROSOFT_TRANSLATE_API_KEY: ${MICROSOFT_TRANSLATE_API_KEY}
      GOOGLE_TRANSLATE_API_KEY: ${GOOGLE_TRANSLATE_API_KEY}
    ports:
      - 9001:9001
    volumes:
      - .:/Zeeguu-API
      - ./data/zeeguu/esV8:/zeeguu-data
    entrypoint: "python /Zeeguu-API/start.py"
    networks:
      - zeeguu_backend
    depends_on:
      - elasticsearch_v8
      - embedding_api
      - readability_server
    mem_limit: 2048m

  readability_server: 
    image: aecrimus/readability_server
    ports:
      - 3456:3456
    networks: 
      - zeeguu_backend
    restart: unless-stopped
    mem_limit: 1024m

  elasticsearch_v8:
    image: elasticsearch:8.12.2
    platform: linux/amd64
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./data/elasticsearch_db_v8/data:/usr/share/elasticsearch/data
    networks:
      - zeeguu_backend
    restart: unless-stopped
    mem_limit: 2048m


  dev_play:
    image: zeeguu_api_dev
    environment:
      ZEEGUU_CONFIG: /Zeeguu-API/default_docker.cfg
    volumes:
      - .:/Zeeguu-API
      - ./data/zeeguu:/zeeguu-data
    entrypoint: "python tools/_playground.py"
    depends_on:
      - elasticsearch_v8
      - embedding_api
      - readability_server
    networks:
      - zeeguu_backend

  # docker-compose run --rm dev_bash
  dev_bash:
    image: zeeguu_api_dev
    stdin_open: true # docker run -i
    tty: true # docker run -t

    environment:
      ZEEGUU_CONFIG: /Zeeguu-API/default_docker.cfg

    volumes:
      - .:/Zeeguu-API
      - ./data/zeeguu:/zeeguu-data
    entrypoint: "bash"
    networks:
      - zeeguu_backend

  dev_test:
    image: zeeguu_api_dev
    environment:
      ZEEGUU_CONFIG: /Zeeguu-API/default_docker.cfg

    volumes:
      - .:/Zeeguu-API
      - ./data/zeeguu:/zeeguu-data
    entrypoint: "./run_tests.sh"
    networks:
      - zeeguu_backend

  dev_init_es:
    image: zeeguu_api_dev
    environment:
      ZEEGUU_CONFIG: /Zeeguu-API/default_docker.cfg
      ZEEGUU_ES_CONN_STRING: "http://elasticsearch_v8:9200"
      ZEEGUU_EMB_API_CONN_STRING: "http://embedding_api:3654"
    volumes:
      - .:/Zeeguu-API
      - ./data/zeeguu/esV8:/zeeguu-data
      - ./Users:/userslalal
    entrypoint: "python tools/mysql_to_elastic_new_topics.py"
    networks:
      - zeeguu_backend
    depends_on:
      - elasticsearch_v8
      - embedding_api
    
  embedding_api:
    image: zeeguu_api_sem_emb
    environment:
      SEMANTIC_EMB_API_PORT: 3654
    ports:
      - 3654:3654
    entrypoint: "python ./semantic-emb-api/app/app.py"
    volumes:
      - .:/Zeeguu-API
      - ./data/zeeguu/language-models:/semantic-emb-api/semantic-emb-api/app/semantic_vector/binaries
    networks:
      - zeeguu_backend

  dev_server_pre:
    image: zeeguu_api_dev
    environment:
      ZEEGUU_CONFIG: /Zeeguu-API/default_docker_v8.cfg
      ZEEGUU_ES_CONN_STRING: "http://elasticsearch_v8_pre:9205"
      ZEEGUU_EMB_API_CONN_STRING: "http://embedding_api:3654"
      PYTHONUNBUFFERED: 1
      MICROSOFT_TRANSLATE_API_KEY: ${MICROSOFT_TRANSLATE_API_KEY}
      GOOGLE_TRANSLATE_API_KEY: ${GOOGLE_TRANSLATE_API_KEY}
    ports:
      - 9005:9005
    volumes:
      - .:/Zeeguu-API
      - ./data/zeeguu/esV8:/zeeguu-data
    entrypoint: "python /Zeeguu-API/start.py"
    networks:
      - zeeguu_backend
    depends_on:
      - elasticsearch_v8_pre
      - embedding_api
      - readability_server
    mem_limit: 2048m

  elasticsearch_v8_pre:
    image: elasticsearch:8.12.2
    platform: linux/amd64
    ports:
      - 9205:9205
      - 9305:9305
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.port=9205
    volumes:
      - ./data/elasticsearch_db_v8/data:/usr/share/elasticsearch/data
    networks:
      - zeeguu_backend
    restart: unless-stopped
    mem_limit: 2048m
    

networks:
  zeeguu_backend:
