name: Create diagram

permissions:
  contents: write

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  get_data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github,.githooks"
          should_push: true
          
      - name: Upload diagram artifact
        uses: actions/upload-artifact@v4       # migrate to v4 to avoid v3 bugs
        with:
          name: repo-diagram                    # choose any valid name
          path: diagram.svg