name: Create diagram

permissions:
  contents: write

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  get_data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      
      # ZEEGUU DIAGRAM #
      - name: Update general diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github,.githooks"
          output_file: "diagram.svg"
          should_push: true

      - name: Upload general diagram artifact
        uses: actions/upload-artifact@v4       # migrate to v4 to avoid v3 bugs
        with:
          name: repo-diagram                    # choose any valid name
          path: diagram.svg

      # ZEEGUU CORE DIAGRAM #
      - name: Update core diagram
        uses: githubocto/repo-visualizer@main
        with:
          root_path: "zeeguu/core"
          excluded_paths: "ignore,.github,.githooks,static,tools,"
          output_file: "core-diagram.svg"
          should_push: true
  
      - name: Upload general diagram artifact
        uses: actions/upload-artifact@v4       # migrate to v4 to avoid v3 bugs
        with:
          name: repo-diagram-core                    # choose any valid name
          path: core-diagram.svg
      
