name: Create diagram

permissions:
  contents: write

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  get_data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github,.githooks"
          should_push: true
          commit_message: "chore: update repository diagram" 
          artifact_name: "repo-diagram"